### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by roggen-yang** [everystreet/go-proj#2]
# github.com/everystreet/go-proj/v6/cproj
../../../../pkg/mod/github.com/everystreet/go-proj/v6@v6.0.0/cproj/cgo_helpers.go:8:18: fatal error: proj.h: No such file or directory
compilation terminated.

**Comment by joe-mann** [comment]
Hi @roggen-yang,

It looks like you haven't installed the PROJ dev package, or haven't configured your environment correctly. Since your error is about an unknown header file, you may just need to add an include `-I` option to your `CGO_CFLAGS`.

Firstly verify that PROJ is installed; see instructions here: https://proj.org/install.html. Then if you still have problems, let me know and I can try to help.

**Comment by joe-mann** [comment]
Please feel free to reopen this issue if you're still experiencing problems.

**Comment by pjrobertson** [comment]
I know this is a bit late, but I just came across this issue.

I'm on macOS 12.6.7.

I ran `brew install proj` then re-installed the package and it worked. Thanks :)
